openapi: 3.1.0
info:
  title: Examples of changes in OpenAPI 3.1
  summary: 3.1 introduced a summary field to the Info node
  version: 1.0.0
  # license:
  #   name: Apache 2.0
  #   identifier: Apache-2.0
# jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
components:
  schemas:
    BasicSchema:
      description: "My basic schema"
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    ReferencedSchema:
      description: "My referenced schema"
      $ref: "#/components/schemas/BasicSchema"
    DoubleReferencedSchema:
      description: "My double referenced schema"
      $ref: "#/components/schemas/ReferencedSchema"
    AnotherSchema:
      $ref: "#/components/schemas/DoubleReferencedSchema"
    AndAnotherSchema:
      $ref: "#/components/schemas/AnotherSchema"
    SelfReferencingSchema:
      type: object
      properties:
        recursive_item:
          $ref: "#/components/schemas/SelfReferencingSchema"
    # WithDialect:
    #   $schema: https://spec.openapis.org/oas/3.1/dialect/base
    #   type: string
    # Const:
    #   const: "test"
    # MultipleTypes:
    #   type:
    #     - string
    #     - null
    # Number:
    #   type: integer
    #   multipleOf: 5
    #   maximum: 110
    #   exclusiveMaximum: 111
    #   minimum: 10
    #   exclusiveMinimum: 9
    # String:
    #   type: string
    #   maxLength: 10
    #   minLength: 5
    #   pattern: "[a-z]*"
    # Array:
    #   type: array
    #   maxItems: 10
    #   minItems: 1
    #   uniqueItems: true
    #   contains:
    #     const: "test"
    #   minContains: 1
    #   maxContains: 1
    #   prefixItems:
    #     - const: "item"
    #     type: string
    #   items:
    #     type: string
    #   unevaluatedItems:
    #     type: string
     # Add object
     # Add content types
     # Add $ref usage (plain, merged, defs)
     # Add compound things: anyOf, oneOf, not, if, then, else
