openapi: 3.1.0
info:
  title: Schema Dialects Example
  version: 1.0.0
jsonSchemaDialect: "https://json-schema.org/draft/2020-12/schema"
components:
  schemas:
    DefaultDialect:
      type: string
    AnotherDefaultDialect:
      type: string
    DefinedDialect:
      $schema: "https://spec.openapis.org/oas/3.1/dialect/base"
      type: string
    CustomDialect1:
      $schema: "https://example.com/custom-dialect"
      type: string
    CustomDialect2:
      $schema: "https://example.com/custom-dialect"
      type: string
